---
# tasks file for lighthouse
- name: Check Lighthouse config exists
  register: lh_exists
  ansible.builtin.file:
    path: "{{ lighthouse_path }}/app.js"
  ignore_errors: true
- name: lighthouse | Copy from git
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_path }}"
  when: lh_exists.state == "absent"    
- name: Change lighthouse default host
  when: lh_exists.state == "absent"
  ansible.builtin.replace:
    path: "{{ lighthouse_path }}/app.js"
    regexp: '127\.0\.0\.1:8123\/'
    replace: "{{ hostvars['clickhouse-01'].ansible_host }}:{{ clickhouse_port }}/?user={{ vector_user }}&password={{ vector_password }}"
    unsafe_writes: true
  notify: Restart Nginx with Lighthouse service
- name: lighthouse | Create lighthouse config
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: Restart Nginx with Lighthouse service      
- name: Print address to connect
  ansible.builtin.debug:
    msg: "Lighthouse is available at http://{{ ansible_host }}:{{ lighthouse_port }}/"